FROM alpine AS build1
RUN touch /tmp/first.txt
RUN sleep 10
 
FROM alpine AS build2
RUN touch /tmp/second.txt
RUN sleep 10
 
FROM alpine AS final
COPY --from=build1 /tmp/first.txt /tmp/
COPY --from=build2 /tmp/second.txt /tmp/